### ISSUE TITLE
to do, documentation: synchronization

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1464]
This is the ticket used to track issues/topics that need to go in the section of the manual that discusses synchronization. Currently we are envisioning this section under **Kiosk**.

### Related tickets in the documentation project:

- [ ] #48 
- [ ] #701 (but this also relates to the gallery so stays in triage for now)
- [ ] #735 
- [ ] #753 (but also relates to image upload and QR codes so stays in triage for now)
- [ ] #754 
- [ ] #823 
- [ ] #931 (tangentially related so stays in triage for now)

### Related old wiki manual pages:

- [ ] The Synchronization Cycle (SK): https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=the_synchronization_cycle

Huh I expected more wiki pages to be relevant but apparently not?

### Categories of documentation needed for this:

- [ ] text

The timezone per dock/workstation section is a subsection of this. This section should also probably include a link to the no need for the internet! section.
