### ISSUE TITLE
to do, documentation: FAQs

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1480]
This is the ticket used to track issues/topics that need to go in the section of the manual that discusses FAQs. Currently we are envisioning this section under **Basic Recording Stuff** (but I am not sure if this is where it should go).

### Related tickets in the documentation project:

- [ ] #699 - how to reset a password if a user forget theirs?
- [ ] #769 - is there an iPad orientation best suited to the recording software?
- [ ] #1262 - is there a way to link features to a unit/change the links between a unit and its features?
- [ ] #1094 - how to find out which locus relations are problematic?

### Related old wiki manual pages:

- [ ] Troubleshooting and FAQ (LB): https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:user_manual:troubleshooting
- [ ] Frequently Asked Questions (FAQ) (SK): https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=for_users#frequently_asked_questions_faq
- [ ] Frequently Asked Questions for admins (SK): https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=for_admins

### Categories of documentation needed for this:

- [ ] text
- [ ] images (only if a screenshot is needed to illustrate any of these)

I can see it being useful to split this particular page between questions that might be more common to regular users and those more relevant for admins, unless we sort questions by topics too.

**Comment by lbestock** [comment]
Are locus relations problems really a FAQ or are those just issues with projects that already had data in there when the current handling was devised?

**Comment by luizaogs** [comment]
Oh is it only useful in that case? I don't know. I'll remove it (the ticket is in the locus ticket, so we won't lose it).

**Comment by lbestock** [comment]
It was a question! Don't remove stuff yet.

**Comment by luizaogs** [comment]
I put it back :)

**Comment by lbestock** [comment]
I am really not sure what to do on this front. Many of the above questions are obsolete or so project specific that "frequent" is impossible. The questions and answers guide is more comprehensive than a FAQ but would have lots of overlap. Actually asked questions are trickling in.
#1642 would be a FAQ for any project set up to have locus numbers that are unique across a project independent of unit numbers.
