### ISSUE TITLE
implement filename attribute: reporting

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1614]
- [x] depends on the report setting "render_filename". It can be "descriptive", "filename" and "uid". 
- [x] As a general rule: If nothing can be rendered  the whole row in a list of files is dropped. The report leads to a warning in this case but is completed.
- [x] implement it also as a key-value mapping because that would work in Excel.

documented here [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:reporting_mapping_definition_pdf#render_filename](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:reporting_mapping_definition_pdf#render_filename)

**Comment by urapadmin** [comment]
### kiosk 0.19
- this is hard to test for anybody but myself. It is best tested in USTP with the context sheet report. So I refer to: #1530

**Comment by urapadmin** [comment]
### todo user manual / tutorial:
This really needs an explanation. Something from the archaeologists point of view like "how to manage drawing numbers as filenames".

**Comment by urapadmin** [comment]
@lbestock successfully tested the particular filename attribute, so this can be closed.
