### ISSUE TITLE
✅✅✅ weekend project checklist ✅✅✅

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1695]
Things I need to do before the projects can actually leave:

per project:
- [x] set file picking for all projects to contextuals / low
- [x] make sure to install the latest filemaker template and synchronize the patches back in
- [x] #1675 
- [x] #1684 
- [x] #1673 
- [x] #1676 
- [x] USTP only: set the header_color to dark
- [x] make sure that kiosk starts with the Hub and not with the file repos
- [x] make sure the latest requirements.txt was used to install kiosk (Flask 2)
- [x] make sure that redis is really not storing its keys on all servers (save="" must be active!)
- [x] make sure that kiosk/subnet is set to the correct sub net 
- [x] make sure that syncmanager/ports is set to "defaulT", "*", reporting
- [x] make sure that the VMs have the correct network config
- [x] make sure Splashtop is installed on the host
- [x] install 0.25.2 as a patch (to test that patches work)
- [x] check that "backup" is automatically pointing to the right path
- [x] save the latest configuration on the backup drive
- [x] clone server so that I have access to it
- [x] test splashtop

after everything
- [x] make sure all backup harddrives are at the same stage
- [x] equip every project with a virtual machine file on the backup drive that could be used for emergencies (use USTP as blueprint)
