### ISSUE TITLE
checklist for update of local PACHA server on 09.July

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1741]
- [x] new dsd with new fields and datatypes
- [x] install new recording template
- [x] prepare workstation to get patches and change a few things:
- [x] check backup path and drive

change constants:
- [x] change help/help_elevations_short_description to `Please enter elevations in m`
- [x] change help/help_measurements_short_description to `Please enter measurements in m or m³`
- [x] change identification method for sample
- [x] change identification method for special find
