### ISSUE TITLE
KHPP 2023 configuration updates

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2038]
Testing KHPP, which has been massively updated. This ticket is to track configuration changes that are needed so they can be checked off once applied.
- [x] locus type: architecture should have formation process disabled.
- [x] locus type: burial should have formation process disabled.
- [x] did QC exist last time for Leslie? It is set moderately. My instinct is to leave it alone but I want to know if they used it last time.
- [x] "number of bags" is turned on for all bulk types and should be turned off for all - that's USTP-style bag numbering.
- [x] weight on CM ceramics needs to be disconnected from ceramics recording. 
- [x] Squirrel368 will be doing the ceramics so we could turn preprocessing off, or conversely we could just leave it on and visible even though it won't be used. Yeah, that one.
- [x] Once #2040 is attended to, change value lists for CM material type so that samples are no longer materials. There are two: archaeobot and sample (other).
- [x] #2041 might be just a configuration issue.
- [x] Add "equivalent to" as a locus relationship in valuelists. But see #1989 because Lutz said there that he had already done it and it's absent.
- [x] configure inverse relationship for locus relation type "other" (should be, wait for it, "other")
- [x] temporary free input is a possibility now. I fear this will only confuse things for KHPP, and as they will not be putting legacy data into the database I wonder if we can/should turn it off.
- [x] elevations: simple
- [x] check on registration codes. When I go to CM registration there is a dropdown menu for "done" that includes only two lines and neither one of them is a valid registration code.
- [x] ceramics pops up (PASU-style) in registration and see above, Squirrel923, we don't need it.
- [x] coordinates does not have an ID method. Does it need one? What is a coordinate ID method? (This is a question I want to ask not a problem to be solved, since importing CCVs was the original way to get coordinates in but we also envision free-inputting them sometimes and there is a + button there in coordinates in the recording system.)
- [x] configure volume/weight so that volume and weight are not shown together for the same thing (currently all samples, and I believe soil as a material). You need to know which one they want for samples, though!
- [x] Give them a photograph button in registration. They used "dear registrar" for that.
- [x] Configure so that dropdowns do not work in registration, are just display.
