### ISSUE TITLE
USTP: ToDo Field Preparation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2162]
This is a todo list of things we need not to forget when preparing the field system.

- [x] install latest finds report
- [x] touch-everything-at-least-once-test with latest recording app
- [x] test with synchronization on first local VM version of the project
- [x] go through configuration and make sure that there are no places they use the year in identification; change season start date
- [x] make sure that the correct begin of the new season is configured in PASU
- [x] check locus type configuration in the recording
- [x] #2191
- [x] "Free input" for coordinates.
- [x] add #2181 
- [x] configure them a to do/done photogrammetry model made in registration
- [x] configure "category 1" and "category 2" labels in preprocessing
- [x] make sure that the automatic updates in the VM are delayed as long as possible
- [x] SOS Software
- [x] copy the final VM to the backup hard drive as master vm
- [x] copy the final VM folder to our Backup Drive
- [x] make sure the latest template is on the backup drive under installers, and Kiosk, too.
- [x] one last start and check
- [x] Print server fact sheet page 1

**Comment by luizaogs** [comment]
I just went through everything for USTP as I had done for PASU earlier, and besides the tickets I opened I think the rest is good to go.

**Comment by lbestock** [comment]
ID method coordinate in configuration is gobbledygook. Is that a problem?

**Comment by urapadmin** [comment]
yes. That means that new coordinates won't get proper identifiers

**Comment by urapadmin** [comment]
if we don't know what identifiers a project wants to use there, select at least free input.

**Comment by lbestock** [comment]
So I keep track of my own progress, my head being not in the clearest state:
As of 2:45pm on the 6th I have made the configuration changes needed, done one synchronization round using the local server and Bridge, and have backed up.
Next step is to create a bunch of bogus data including SLR photos like a maniac and see what happens.
Then I will need to restore to the backup.

**Comment by lbestock** [comment]
Restored to backup.
