### ISSUE TITLE
PASU: todo field preparation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2163]
### todo 2023
Don't forget when preparing the field system:
- [x] install latest report versions
- [x] install the list of SUs report
- [x] touch-everything-at-least-once-test with latest recording app
- [x] test with synchronization on first local VM version of the project
- [x] add #2181 
- [x] make sure that the automatic updates in the VM are delayed as long as possible
- [x] SOS Software
- [x] copy the final VM to the backup hard drive as master vm
- [x] copy the final VM folder to our Backup Drive
- [x] make sure the latest template is on the backup drive under installers, and Kiosk, too.
- [x] Config: Change identification methods for samples and small finds
- [x] Print server fact sheet page 1

**Comment by urapadmin** [comment]
@arch-kiosk/test Pleeeease test PASU and USTP recording app (I know, you can't synchronize because you are on real data ...) on an ipad and try to look at it from an excavators perspective. Does it still make sense. Are the identifiers visible? Does it work? 
So the test is about touching everything at least once and see if all our changes and improvements make sense the way the project is configured.

**Comment by luizaogs** [comment]
Ok, I've touched everything and given you a bunch of tickets. Besides those I think things are good. I now have to go get ready for a birthday gathering I do not wish to go to, but I will do USTP later.
