### ISSUE TITLE
recording: to-do list in the recording app itself

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2414]
I think I had already mentioned this after the MKAP season, but I think it would be super helpful to have a built-in to-do list in the recording that one can use to check things off. I had originally thought of it on a unit level, but a site level might actually be more useful. I envision it as something that can be accessed on the home page somewhere. 

Today, for instance, we had to make a list of photographs we still want to take and drawings we want to make and we used site notes because we didn't want to use paper (!). Which works, but a dedicated little module might be better -- especially if we can check things off, too, and maybe even navigate to identifiers mentioned in the list.

**Comment by urapadmin** [comment]
sounds like something one would want on hand everywhere. Like the pinboard.

**Comment by urapadmin** [comment]
@lbestock: Seconded?

**Comment by luizaogs** [comment]
Oh sure, I was thinking of the hamburger menu too. But accessing it from home, so before actually entering a specific record, would also be good.

**Comment by lbestock** [comment]
Would be fantastic. I do immediately think complications... As in, is there one universal synchronized to do list? That has some use, but also how do you find what YOU are supposed to do then? Better: can tasks be assigned to individual people so you can keep your own and/or be assigned something by the director? (I want this live in director's view, of course, so I can get all angry and immediately turn my anger into clickable "to do"s that pop up for the perpetrator.)

**Comment by luizaogs** [comment]
Could we then have the option to either see an individual user’s to-do list or the overall list?

**Comment by urapadmin** [comment]
> Would be fantastic. I do immediately think complications... As in, is there one universal synchronized to do list? That has some use, but also how do you find what YOU are supposed to do then? Better: can tasks be assigned to individual people so you can keep your own and/or be assigned something by the director? (I want this live in director's view, of course, so I can get all angry and immediately turn my anger into clickable "to do"s that pop up for the perpetrator.)

Let's keep it simple and not turn Kiosk into a communication system. I think in the field you better talk to your field people in regular meetings and then you can go through your records. Has some value. The talking, I mean.

But if we start with a project-wide to do list and limit ourselves to the recording app first (we do not manipulate data on the server side) and give the thing a couple of columns like "who?" and "category" it should not be too hard to do and perhaps solve 80% of all use cases.

**Comment by urapadmin** [comment]
not this year, though.

**Comment by luizaogs** [comment]
Lutz, is there any chance we can get this for MKAP? I just realized this was the only request from last season that was actually deemed worth doing (so far, at least). It would be a big help but I realize I should have brought it up sooner, so if not that’s fine.

**Comment by urapadmin** [comment]
ja, I was planning to look into MKAP anyhow this week. The todo list should be doable.

**Comment by urapadmin** [comment]
so this is what I plan to do:

- [ ] an open to do list, accessible to all users likewise (so no privileges or anything). 
- [ ] A new button in the burger menu and one on the start page gives access
- [ ] I hesitate to bind this to site or unit at all. I would just leave it open.
- [ ] fields are: date (meaning the due date or the date when this is relevant or so), todo title, todo description, priority?, "involved", a state, which ends in done but can have other configurable values, too.
- [ ] the "involved" field can be empty, a single user or many users or even something entirely different (like the name of somebody who isn't a user or the name of a group etc.). So that is supposed to be basically a text field with stuff in it. Often enough that stuff is just your user name, but that's not formalized
- [ ] sort by all fields (except the description)
- [ ] filter by all text fields
- [ ] the description field can have context mentioned and gets the button that allow you to jump to a context

Am I missing something? comments welcome.

**Comment by luizaogs** [comment]
Sounds great to me. Can we have context AND unit mentioned (with the footsteps)? (By context do you mean all archaeological identifies anyhow? I can't remember. Anyway.)

**Comment by urapadmin** [comment]
> Sounds great to me. Can we have context AND unit mentioned (with the footsteps)? (By context do you mean all archaeological identifies anyhow? I can't remember. Anyway.)

As with narratives: Whatever identifier you mention in the text of the description can be navigated to with the footsteps. I forgot what I called that feature. But it deems me the most flexible solution here.

**Comment by urapadmin** [comment]
### recording app 16.2
- the valuelist "valuelist_todo_states" is one of the rare valuelists that keep their order of appearance. It lists the possible states for a task
- the valuelist "valuelist_todo_priorities" potentially does not keep its order, which should not matter because priorites A,B,C will always be sorted correctly. It would only become an issue if you use something like Z-1, X-4,Q-3. . 
- both valuelists support the "-" entry that makes it easy on iPads to select nothing
- under "visibility" the new "show_todo_list" can be used to hide the to-do buttons for projects that don't want them. Default is "yup", though.
- there is a button on the start page and a button in the burger menu of locus, unit and collected material
- in the to-do list the button for reference navigation is only visible if there is actually text in the to do description
- clicking on the reference navigation does not open a new popup (because we are already in a popup) but blends the navigation list into the existing popup. That's why there is a button to go back in the header of the reference navigation. It's not the most appealing solution, visually, but it works everywhere.
- there is a "find" which searches description and title for a word or phrase (but not parts of a word!)
- there is a heart button that selects all tasks that have the current user as participant
- in the filter button you can filter from - to and by participants. Participants must be a full user name or word. "Bob" would not find "Bobbins"
- you can only delete a to-to as a registrar. Otherwise you won't see the button
- "show finished tasks" includes, well,  finished tasks. By default they are hidden.
- you can sort in ascending order by clicking on the headers. Note that an empty field is first in an ascending order.
- the refresh button in the upper left re-applies the current filter settings. After typing in new to-do items that might be useful to have the filters applied to the new todo items as well.
- I am always unsure if it is better to erase all filters on entering such a form or if the filters that were applied last should still be active. Here I have decided to clear them whenever you go into the to-do list. Let me know if you think it better the other way around.

**Comment by luizaogs** [comment]
Reference navigation does not seem to be working (the actual navigation, the buttons are there): 

LA in the description should have given me the option to go to unit LA.

![IMG_0466](https://github.com/user-attachments/assets/ab384bfe-8aa3-456b-acde-acfdfe68d9b0)

![IMG_0467](https://github.com/user-attachments/assets/2386fc3e-badc-4050-8c4b-640f03ff6c0d)

**Comment by luizaogs** [comment]
Still testing the rest.

**Comment by luizaogs** [comment]
The heart also seems to not be working. I'm logged in as logs but neither LOGS nor logs are findable with the heart if I have that as the participant.

**Comment by luizaogs** [comment]
The "done" is not making tasks disappear as soon as I select it. If I just put done as the state for a task it continues hanging out there in the to-do list. If I then check and uncheck the "show finished tasks" button THEN it works properly, and "done" tasks disappear (unless that button is selected).

**Comment by luizaogs** [comment]
That's it, everything else is working. Thank you - this is going to be helpful.

**Comment by urapadmin** [comment]
> The "done" is not making tasks disappear as soon as I select it. If I just put done as the state for a task it continues hanging out there in the to-do list. If I then check and uncheck the "show finished tasks" button THEN it works properly, and "done" tasks disappear (unless that button is selected).

by design. after changing data the filters need to be reapplied. That's what the refresh button does (or changing the filters)

**Comment by urapadmin** [comment]
> Reference navigation does not seem to be working (the actual navigation, the buttons are there):  

LA needs quoting or brackets

**Comment by luizaogs** [comment]
Ok. Then just the heart then, unless I also misunderstood how that is supposed to work.

**Comment by urapadmin** [comment]
No, the heart is indeed broken. It only reacted to "admin". 
Also: the date field isn't okay. It should accept Latin inputs and show the Latin representation underneath.

**Comment by urapadmin** [comment]
### recording app 16.2.1
- I have added a little heart button next to the participant to easily enter ones own user id.
- in this iteration I have switched on automatic re-applying the current filters when a record is saved. I find it sometimes a bit weird when my changes make my record disappear. But that's just my own intuition and I am not the one who uses it. Just let me know, which you prefer. @lbestock ? BTW. That still won't make the record vanish as soon as you select "done". only after you leave (click in header or go to different record) and thus save the record do the filters get reapplied. 
- date field shows Latin representation and accepts Latin input
- heart button should work now

**Comment by luizaogs** [comment]
Works now.
