### ISSUE TITLE
ELRI: Task list for first season

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2650]
This is the list of things to do for ELRI (Economic Landscapes of Roman Istria)

- [x] set up online kiosk
- [x] first configuration according to the context sheet and comments we got
- [x] #2661
- [x] @lbestock configures lists and terms
- [x] @urapadmin configures ID methods
- [x] @urapadmin please delete all locus types EXCEPT: deposit, fill, cut, structural. 
- [x] Kiosk: custom settings for colours etc.
- [x] Kiosk: custom settings for regex if needed
- [x] What is the exact timing? ELRI is first, then USTP then AAC? Will Candace come back between ELRI and USTP? I hope so.
- [ ] #2684
- [x] #2654
- [x] #2655
- [x] "pottery" opens up the ceramics preprocessing.
- [x] "show_material_specified" -> nope
- [x] "label_sector" -> "area"
- [x] #2656
- [x] #2657 
- [x] #2659
- [x] #2660 
- [x] #2670
- [x] SOS software: install and test on the Loaner Mac.

**Comment by lbestock** [comment]
A few notes on configuration after a zoom with Candace and a discussion at Hillside.
@lbestock will handle terminology
@urapadmin will handle numbering, which is a hybrid between USTP and URAP: context numbers are independent of unit numbers, but CM numbers are sequential numbered within a context (no independent number runs for bulk/special finds/samples).
@urapadmin will also handle ceramics, which should have preprocessing in the same way as USTP.

Meeting with Candace 10am Wednesday 25 IV 24, by which time we will have a configured system to walk through.

**Comment by urapadmin** [comment]
what about the "void" locus type? Did you add that but it isn't needed? I delete it.

**Comment by urapadmin** [comment]
so:
- trenches are free input
- loci are numbers dependent on a predefined number list
- collected materials are numbered sequentially on the basis of their locus

**Comment by urapadmin** [comment]
as for timing: 

> I’ll be back from Croatia on May 25 and can swap out iPads before heading to Italy on June 8 or so if necessary.

**Comment by cmrice-arch** [comment]
I don’t think I’ve asked this yet — what is the setup for designating context numbers by trench? 


__
Candace M. Rice
Assistant Professor of Archaeology and Classics

Joukowsky Institute for Archaeology and the Ancient World
Brown University | Box 1837 | 60 George Street | Providence, RI  02912 | USA

**Comment by urapadmin** [comment]
> I don’t think I’ve asked this yet — what is the setup for designating context numbers by trench?

4 digits based on a preassigned numbering list, as in USTP. So starts with 0001 for a first device and with whatever you choose, e.g. 0100, for device 2.

**Comment by lbestock** [comment]
@cmrice-arch The 4 digits is what we configured so far for you. But, it's very easy to have context numbers that are sequential by trench (which is what we do at Uronarti). Then you have say Trench AA, and contexts would be AA-001, AA-002, AA-003 etc. Do you know what naming convention you will use for trenches? (It isn't even necessary to decide that yet if you would prefer this numbering. We can set it so it is just "trench name"-001, etc.)

**Comment by cmrice-arch** [comment]
Does this work to add @amclean6787 to the thread?

**Comment by lbestock** [comment]
Andrew, let us know it works by responding! But it should.
So, would you like "Trench 1-001" etc or "1-001"? Or "T1-001". 
I totally agree (having arrived at the same solution for my own work after not having had it for decades) that using the trench as a prefix for context numbers is the best combination of succinct and functional/meaningful.

**Comment by amclean6787** [comment]
> Andrew, let us know it works by responding! But it should. So, would you like "Trench 1-001" etc or "1-001"? Or "T1-001". I totally agree (having arrived at the same solution for my own work after not having had it for decades) that using the trench as a prefix for context numbers is the best combination of succinct and functional/meaningful.

Yes, it seems to have worked! From my side, "T1-001" looks best, but any of the options would be good

**Comment by cmrice-arch** [comment]
I was also going to say T1-001, but looking at it in writing now that the coffee is kicking in,  it occurs to me that we should keep it strictly numerical in the interest of a bi-lingual team. The Croatian word for trench is sonda, so the T might just cause confusion.

**Comment by amclean6787** [comment]
Very good point. Happy to keep it numerical

**Comment by urapadmin** [comment]
@lbestock This is not how we configured it, or did we? The context numbers are currently not related to the trench. If we relate them to the trench we won't need the identifier lists to assign the context numbers.

**Comment by lbestock** [comment]
I have to check. We originally configured it to need identifier lists. I changed that either while talking to Candace or before, but I can't remember if I synchronized this.

**Comment by urapadmin** [comment]
@luizaogs Can you please check if the things that are marked as checked on top (the ones that don't have their own ticket and that you can actually test) are actually working? I fear it will be overlooked otherwise.

**Comment by luizaogs** [comment]
Yes, they look fine to me.

**Comment by lbestock** [comment]
> @lbestock This is not how we configured it, or did we? The context numbers are currently not related to the trench. If we relate them to the trench we won't need the identifier lists to assign the context numbers.

Yup - this is all properly configured. ELRI is ready to put on the local server for testing!

**Comment by urapadmin** [comment]
then I'll do that

**Comment by urapadmin** [comment]
@luizaogs: If you still have a nerve, could you please click through Q&V on ELRI (you would have to create records first) and test the terminology in Q&V in ELRI? So names for locus, unit, collected material, dayplans and check if they are plausible? If you encounter URAP terminology or strange variable expressions (something like '#(constants/bla bla)' instead of proper English, please let me know where. This is really not crucial, so don't wreck any of your weekend because of it.

**Comment by urapadmin** [comment]
@arch-kiosk/test I leave ELRI online for testing purposes. But the data is now safely transferred, so you don't have to treat the online system as a production system anymore. Meaning: You can create test data as you wish, I'll replace it later again.

**Comment by luizaogs** [comment]
> @luizaogs: If you still have a nerve, could you please click through Q&V on ELRI (you would have to create records first) and test the terminology in Q&V in ELRI? So names for locus, unit, collected material, dayplans and check if they are plausible? If you encounter URAP terminology or strange variable expressions (something like '#(constants/bla bla)' instead of proper English, please let me know where. This is really not crucial, so don't wreck any of your weekend because of it.

Yeah, I can do this tonight. Currently suffering through a volume on gender in Spanish.

**Comment by luizaogs** [comment]
@urapadmin terminology in Q&V looks fine and matches that in FM.
