### ISSUE TITLE
PASU: Task list for Season 2024

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2695]
Deadline here is May 24th (graduation day).

- [x] Because of #2699 and #2691 this needs to be tested thoroughly. Particularly all types of file import.
- [x] PASU: set up virtual machine
- [x] #2382 
- [x] #2381 
- [x] #2253
- [x] Make a special instruction sheet that explains what to do with the virtual machine when they start
- [x] look at the tickets in the PASU project
- [x] configuration #2706

**Comment by urapadmin** [comment]
@lbestock the virtual machine is available under http://192.168.11.102 if you connect to "kiosknet1".

**Comment by lbestock** [comment]
Hmpf not responding. I think you powered down the computer, like a not-Mac-user.

**Comment by urapadmin** [comment]
yes, the climate ...
