### ISSUE TITLE
USTP 2024 Task List

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2713]
- ❗ note that USTP is sharing a SSD with AAC, so: #2743 
- [x] set up local server 
- [x] install fm template without patches active
- [x] set up local server on emergency drive
- [x] copy virtual machine master to backup drive
- [x] copy vm to our field project drive
- [x] update server fact sheet
  - [x] mention again that if the preparing and download times are getting too long they should contact us.
- [x] instructions on how to manage two projects with one Virtual Machine SSD
