### ISSUE TITLE
AAC Task List 2024

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2743]
- USTP shares a SSD with AAC, so see #2713 

- [x] set up local server 
- [x] install fm template without patches active
- [ ] set up local server on emergency drive (there was no space for that on the emergency drive)
- [x] copy virtual machine master to backup drive
- [x] copy vm to our field project drive
- [x] update server fact sheet
  - [x] mention again that if the preparing and download times are getting too long they should contact us.
- [ ] instructions on how to manage two projects with one Virtual Machine SSD
