### ISSUE TITLE
New project checklist: RLIIM

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#3016]
We have a new project!
Petra Creamer, Assistant Professor at Emory University
Rural Landscapes of Iron Age Imperial Mesopotamia.

I pointed out that this was an unpronounceable acronym about to be perpetrated and she laughed and took the “age” out, so we have the still baroque but more bearable RLIIM. With two “i”s! Rural Landscapes seem to be where Mesopotamians are at right now.

- [x] request server from Robert (@urapadmin this will still be on Beset, right?)
- [x] Receive documentation via googledrive from Petra
- [x] First project meeting for concordance, 24 January 2025

**Comment by urapadmin** [comment]
wasn't there another project coming? I like bundling things for Robert.

**Comment by lbestock** [comment]
Selinunte and Samothrace I am meeting with in late January. And if we take either one or both of those on, it will be an order of magnitude bigger than anything we have done (including Abydos) and a little Beset division will not be the answer.

But I am actually having lunch with someone from Brandeis who has mentioned interest, though that’s not the whole reason we made a lunch date. So maybe we can give Robert two.

**Comment by lbestock** [comment]
Yup! Two to request. Other is not quite so certain it will actually happen, as they are concerned about prices for iPads. But they are real enough to make it worth setting up a server and basic template for my next meeting with her. New ticket.

**Comment by lbestock** [comment]
Meeting with Petra is 24 January 25 at 2pm. What do we need to do before that? Documentation is on the way. I would want to start customizing on the basis of the documentation tomorrow so that we walk through concordance with an already partly customized Kiosk to show. @urapadmin can you get the server up and running with a blank Kiosk today?

**Comment by urapadmin** [comment]
can we get a logo from that university for our collection?

**Comment by lbestock** [comment]
I have asked for the logo.

Meeting on the 24th was really good - concordance was basically finished on the basis of the context sheets and ceramics stuff they provided prior to the meeting. Some things of import for us:

They are going to test out warecodes in the next weeks. That was quickly configured for them. It would be very cool if another project uses warecodes, and if they do, we want to think about how to get together the tens of thousands of sherds they already have in their Excel with what will be recorded in Kiosk.

They leave for the field 27 April 2025.

They will be working with students in March to input old data. They will reopen two of their previous trenches this season, as well as starting new ones. So the old data have to be in there. Legacy data input starts 5 March (more approximate than the leaving for the season date).

Petra's main question was what happens if they are using the server laptop in multiple capacities, and she leaves it connected to the internet while firing up Kiosk.

They are PC users.

They have excellent internet at the dig house.

**Comment by urapadmin** [comment]
rliim is using these settings for Kiosk proper right now: 

```
  recording_context_aliases:
    locus: 'locus'
    unit: 'OP'
    locus_photo: 'locus photos'
    dayplan: 'OP photos'
    locus_relations: 'locus relations'
    collected_material_photo: 'collected material & special finds'
    collected_material: 'collected material & special finds'
    unit_narrative: 'OP narrative'
    site_note_photo: 'site note'
    site: 'site map'
    pottery_images: 'pottery'
    tags: 'locus tags'
```

**Comment by urapadmin** [comment]
argl. I don't get it. Why was RLIIM configured to use su_ceramics as database structure? Should it not have been warecode pottery? I have changed it it warecode now. This needs a test. I would not have synchronized.

**Comment by urapadmin** [comment]
- [x] RLIIM local server is configured and boxed
- [x] documentation is updated on the Google Drive
- [ ] check documentation on steps when receiving the Kiosk package
- [ ] Petra must test this while still in the US because of the little glitch we had in the end.
- [ ] send Petra instructions what to do next

**Comment by luizaogs** [comment]
This can be closed, no? (Trying to clean up for Lutz.)
