### ISSUE TITLE
[tracking] finally upload project to github

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#927]
uploading GitHub means going public. So there are things to be solved first!
tracking prerequisites:
- [x] #1164 
- [x] #1215 
- [x] #187 
- [x] https://github.com/arch-kiosk/arch-kiosk-office/issues/1348
- [x] search for "notebook_source" everywhere. That should not be part of anything in the github repos.
- [x] #1726
- [x] #1722 
- [x] in the very end: make a backup of the current repository and then get rid of the git history
- [x] #1724
- [x] initialize server\kiosk as the new git root (currently it is server).
- [x] Do it again in a fresh clone: #1348 
- [x] search for "notebook_source" and "lutz" and such in a new clone of the repo. Nothing should come up
- [x] #1725

**Comment by urapadmin** [comment]
just uploading it won't do. There are other prerequisites to meet:
- [ ] an intro documentation for how to set up a new server
-

**Comment by urapadmin** [comment]
this is not just on me.
what else do we have to think of before we go public?

**Comment by urapadmin** [comment]
see #1164

**Comment by urapadmin** [comment]
don't do this before #1215

**Comment by urapadmin** [comment]
this needs #187 first

**Comment by urapadmin** [comment]
tracking prerequisites:
- [ ] #1164 
- [ ] #1215 
- [ ] #187 
- [ ] clone the local repository and do a file search for typical secrets

**Comment by urapadmin** [comment]
- [ ] something

**Comment by urapadmin** [comment]
### Kiosk 1.2 on github

**Comment by lbestock** [comment]
🤪💃🐝🐙🥂
